[build]
  command = "npm run db:prepare && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"

[functions]
  included_files = ["prisma/dev.db"]

[[plugins]]
  package = "@netlify/plugin-nextjs"
