export const HOMEPAGE_LOCATORS = {
    featuredSection: '[data-testid="featured-properties-section"]',
    featuredGrid: '[data-testid="property-grid"]',
    propertyCards: '[data-testid="property-card"]',
    propertyTitles: '[data-testid="property-card"] h3',
    propertyImages: '[data-testid="property-card"] img',
    propertySkeleton: '[data-testid="featured-properties-section"] [data-testid="property-skeleton"]',
    exploreCta: '[data-testid="explore-properties-cta"]',
    noProperties: '[data-testid="no-properties"]',
    testimonialsSection: '[data-testid="testimonials-section"]',
    testimonialsGrid: '[data-testid="reviews-grid"]',
    reviewCards: '[data-testid="review-card"]',
    reviewTitles: '[data-testid="review-card"] h3',
    reviewSkeleton: '[data-testid="testimonials-section"] [data-testid="review-skeleton"]',
    noReviews: '[data-testid="no-reviews"]',
    featuredHeading: '[data-testid="featured-properties-heading"]',
    featuredSubheading: '[data-testid="featured-properties-subheading"]',
    testimonialsHeading: '[data-testid="testimonials-heading"]',
    testimonialsSubheading: '[data-testid="testimonials-subheading"]',
    homeError: '[data-testid="home-error"]',
} as const;
