export const SERVICES_LOCATORS = {
  servicesPage: '[data-testid="services-page"]',
  introSection: '[data-testid="services-intro-section"]',
  introHeading: '[data-testid="services-intro-heading"]',
  introSubheading: '[data-testid="services-intro-subheading"]',
  quickLinksSection: '[data-testid="services-quick-links-section"]',
  quickLink: '[data-testid^="services-quick-link-"]',
  propertySellingSection: '[data-testid="services-property-selling-section"]',
  propertySellingHeading: '[data-testid="services-property-selling-heading"]',
  propertyManagementSection: '[data-testid="services-property-management-section"]',
  propertyManagementHeading: '[data-testid="services-property-management-heading"]',
  investmentAdvisorySection: '[data-testid="services-investment-advisory-section"]',
  investmentAdvisoryHeading: '[data-testid="services-investment-advisory-heading"]',
  propertySellingGrid: '[data-testid="services-property-selling-section"] div[class*="grid"]',
  propertyManagementGrid: '[data-testid="services-property-management-section"] div[class*="grid"]',
  propertySellingCtaLink: '[data-testid="services-property-selling-cta"] a:not([data-testid])',
  propertySellingCtaButton: '[data-testid="services-property-selling-cta-button"]',
  propertyManagementCtaLink: '[data-testid="services-property-management-cta"] a:not([data-testid])',
  propertyManagementCtaButton: '[data-testid="services-property-management-cta-button"]',
  investmentAdvisoryCtaLink: '[data-testid="services-investment-advisory-left-cta"] a:not([data-testid])',
  investmentAdvisoryCtaButton: '[data-testid="services-investment-advisory-left-cta-button"]',
  bottomCtaSection: '[data-testid="services-bottom-cta-section"]',
  bottomCtaHeading: '[data-testid="services-bottom-cta-heading"]',
  bottomCtaButton: '[data-testid="services-bottom-cta-button"]',
  skeleton: '[data-testid="services-skeleton"]',
  error: '[data-testid="services-error"]',
  errorRetry: '[data-testid="services-error-retry"]',
  empty: '[data-testid="services-empty"]',
} as const;
